### ISSUE TITLE
Need update for crc-bundle-info file creation (extra slash)

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#10]
```console
update_json_description crc-tmp-install-data/
+ cat crc-tmp-install-data//crc-bundle-info.json
+ jq '.clusterInfo.masterHostname = "crc-fdzt7-master-0"'
+ jq '.clusterInfo.sshPrivateKeyFile = "id_rsa_crc"'
+ jq '.clusterInfo.kubeConfig = "kubeconfig"'
+ jq '.clusterInfo.kubeadminPasswordFile = "kubeadmin-password"'
+ jq '.storage.diskImages[0].name = "crc.qcow2"'
+ jq '.storage.diskImages[0].format = "qcow2"'
cat: crc-tmp-install-data//crc-bundle-info.json: No such file or directory
+ rm crc-tmp-install-data//crc-bundle-info.json
rm: cannot remove ‘crc-tmp-install-data//crc-bundle-info.json’: No such file or directory
```

**Comment by cfergeau** [comment]
I don't think this is related to the double /
snc.sh will create a `crc-bundle-info.json` in `crc-tmp-install-data/` and then `create_disk.sh` moves this file to the tarball directory, and adds more metadata to it. Once this is done, `update_json_description` deletes crc-tmp-install-data/crc-bundle-info.json, so you cannot call `update_json_description` multiple times. If you `touch  crc-tmp-install-data/crc-bundle-info.json` first, I expect your test will work.
I can't remember why I added this `rm  $1/crc-bundle-info.json` in `update_json_description` though ;)

**Comment by cfergeau** [comment]
crc-bunudle-info.json is no longer removed from crc-tmp-install-data since commit cdccd9af9 so this should no longer be an issue.
