### ISSUE TITLE
Create a flag to get the quay registry for pulling the artifacts

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#104]
Right now we only have `quay.io/openshift-release-dev/ocp-release` and a QUAY_REGISTRY env to define which registry to use to pull the artifacts, but it would be nice to have it a command option.

Follow up issue for https://github.com/code-ready/snc/pull/103#issuecomment-535039316

**Comment by cfergeau** [comment]
This does not have to be a commandline option. The problem we want to solve is to have a way to let snc.sh know if we want to use an openshift image from:
- an official 4.1 release
- a nightly 4.1 build
- a nightly 4.2 build
The fact that we need a different registry for 3. is an implementation detail imo. We had several issues already regarding to deciding whether to build from a released image and a nightly, it would be nice to fix this once and for all.

**Comment by praveenkumar** [comment]
not needed anymore, closing this.
