### ISSUE TITLE
Resize the disk to 35GB from 31 GB

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#108]
As of now we are resizing the disk to `31GB` but metion `35GB` in our docs, better to increase since from 4.2 side 11 GB space already filled by container images.

**Comment by cfergeau** [comment]
31GB is the maximum VM disk size, but initially the qcow2 file does not occupy that much space as qcow2 is thinly allocated. However, we have additional disk space requirements, we need space for the binary (2GB), the extracted bundle (2GB), the unpacked bundle (11GB), and then the VM disk itself (11GB). This gives us 26GB, so documenting 35GB leaves us with some flexibility for the VM image to grow.

**Comment by praveenkumar** [comment]
Disk resize is now part of our crc codebase so  whatever we have currently is good enough.
