### ISSUE TITLE
Add a env variable which take release tag otherwise date for creating the tarball folder

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#12]
We need to add a env or argument to take the release tag info an then create the directory with that instead using the `date` and also the tarball.

like in case of v4.1.0-rc0 it should be `crc_libvirt_v4.1.0-rc0` instead `crc_libvirt_2019-04-28` and same for tarball.

**Comment by cfergeau** [comment]
This was fixed as part of #15 , though using a git tag rather than an env var.
