### ISSUE TITLE
Add cert recovery script and also unit file to start it.

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#133]
As of now we have cert recovery logic is in the CRC repo side but it would be good if this can be part of the bundle itself, Also it make sense to have it as systemd unit file to control it. 

- https://gist.github.com/cfergeau/fc4ac5379a120dad1381e8ba1fc4789d#file-regenerate-certs-sh

**Comment by cfergeau** [comment]
For the record, I think this is interesting to experiment with, even if I'm not fully sold on replacing go code with a shell script :)

**Comment by praveenkumar** [comment]
Openshift have now better cert rotation support, no manual scripts need to be executed.
