### ISSUE TITLE
Add a bash script linter and CI to validate scripts

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#156]
We should add a shell script linter and also setup a travis CI for same.

- https://github.com/koalaman/shellcheck

**Comment by mtarsel** [comment]
With the addition of a ppc64le machine at the OSU OSL for CI (https://osuosl.org/services/powerdev/) I can work on this issue if you'd like. I think majority of the issues are:` Double quote to prevent globbing and word splitting.`

Once the commits settle down for the 4.6 release, I can push 1 big edit commit. You can assign this to me if you'd like.

@praveenkumar @cfergeau

**Comment by gbraad** [comment]
This might be affected by a choice to use golang instead: https://github.com/code-ready/snc/issues/210

**Comment by mtarsel** [comment]
So I'm working on getting this shellcheck support for ppc64le. As of today, there is no "official release" of shellcheck for ppc64le even tho it is supported.

See: https://github.com/koalaman/shellcheck/issues?q=is%3Aissue+is%3Aopen+ppc64le

which references: https://github.com/code-ready/snc/blob/master/shellcheck.sh#L9

**Comment by guillaumerose** [comment]
We can skip the check for this architecture. Also, it is only used by the CI. It doesn't run in ./snc.sh script.

**Comment by praveenkumar** [comment]
we have now shellcheck in the CI.
