### ISSUE TITLE
Unable to resize disk

### ISSUE THREAD

**Issue by BenHall** [code-ready/snc#168]
I'm trying to resize the CRC disk via guestfish, however I'm getting the error `libguestfs: error: luks_open:`

This is running on `CentOS Linux release 8.1.1911 (Core)`. 

Do you have any suggestions?

**Comment by cfergeau** [comment]
You are hitting https://bugzilla.redhat.com/show_bug.cgi?id=1791353
Since you filed this against snc, you can see how this was worked around https://github.com/code-ready/snc/commit/a25fc4bd7cd904e4903df4041c84c89cf3c18d12

**Comment by BenHall** [comment]
@cfergeau Thanks, but we are using that workaround and still hitting the error

**Comment by cfergeau** [comment]
Please provide the full log of what you are doing.
