### ISSUE TITLE
snc.sh will fail if yq version = `2.10.0` (installed via pip)

### ISSUE THREAD

**Issue by btannous** [code-ready/snc#174]
Issue:
snc.sh will fail if yq version = `2.10.0` which what is available via pip: https://pypi.org/project/yq/

Steps:
- Run .snc.sh
- output seems to run until it hits a `yq write --inplace` block.
- yq/jq do not handle this failure gracefully at version `2.10.0` and pause instead of exiting with a failure
- snc.sh hangs.

See the following as an example (make sure you do not have yq installed):
```shell
❯ pip3 install yq
❯ yq write --inplace crc-tmp-install-data/install-config.yaml baseDomain testing         
jq: Unknown option --inplace                                                                 
Use jq --help for help with command-line options,            
or see the jq manpage, or online docs  at https://stedolan.github.io/jq
```

Since we handle installing yq if it does not exist, we should also be sure that the flags we are using work, or validate that `yq` is the version we expect

**Comment by btannous** [comment]
Looks like https://github.com/code-ready/snc/commit/5afcf63009e275502f3e71a7d9be89e12b54cfed updated yq.

**Comment by gbraad** [comment]
the reason we 'install' the version is that this is normal run from an automated script on a CI/CD environment, and therefore nothing previously existed.

do not expect a 'regular user' to run SNC as it is used to customize the image bundle.

version checks could be added ...

**Comment by btannous** [comment]
that makes sense so given the nature of snc, probably is unnecessary to check.

Then I'm cool to close, if someone was manually running stuff and it didn't work because of this they should at least be able to search and see the issue/resolution in this issue.

- don't use yq from pip
- use one as here: https://github.com/mikefarah/yq/releases

**Comment by cfergeau** [comment]
Main problem is indeed there are 2 different incompatible tools named yq :(

**Comment by cfergeau** [comment]
```
diff --git a/snc.sh b/snc.sh
index 3f2f42e..79d1815 100755
--- a/snc.sh
+++ b/snc.sh
@@ -163,11 +163,9 @@ if ! which ${OC}; then
 fi
 
 # Download yq for manipulating in place yaml configs
-if ! which ${YQ}; then
-    if [[ ! -e yq ]]; then
-        curl -L https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64 -o yq
-        chmod +x yq
-    fi
+if ! "${YQ}" -V; then
+    curl -L https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64 -o yq
+    chmod +x yq
     YQ=./yq
 fi
 ```
would probably do the trick

**Comment by praveenkumar** [comment]
we solved this by always using YQ from current directory so there is no `which YQ`  in the script.
