### ISSUE TITLE
Pull Secret?

### ISSUE THREAD

**Issue by disposab1e** [code-ready/snc#179]
How can I get a pull secret and how can I set this pull secret via OPENSHIFT_PULL_SECRET?

**Comment by disposab1e** [comment]
Found a way :-)

**Comment by cfergeau** [comment]
https://cloud.redhat.com/openshift/install/crc/installer-provisioned is one way of getting access to a pull secret. Once snc can make use of the fedora coreos/okd images, a pull secret will no longer be required.

**Comment by disposab1e** [comment]
Cool! Thx! Works fine until... never stops :-(

Waiting for first CSR request.
+ sleep 2
+ ./oc get csr
+ grep Pending
+ echo 'Waiting for first CSR request.'
