### ISSUE TITLE
luks-open always report 'Not enough available memory to open a keyslot'

### ISSUE THREAD

**Issue by zhangs-ibm** [code-ready/snc#184]
Create a build envirnment at RHEL 8.2 - 64G memory
The `./snc.sh` can be executed without any issue and virsh hosted Openshift works properly.
When create the image by `./createdisk.sh`, it always fail at the step `resize_and_sparsify`, this is the error message:
```
[   8.0] Setting up initial partition table on crc_libvirt_2020-06-23/crc-resizedXjTT.qcow2
[  24.0] Copying /dev/sda1
[  25.2] Copying /dev/sda2
[  25.5] Copying /dev/sda3
[  25.6] Copying /dev/sda4
 100% [#################################################################] 00:00

Resize operation completed with no errors.  Before deleting the old disk, 
carefully check that the resized disk boots and works correctly.
+ '[' 0 -ne 0 ']'
++ echo nokey
++ guestfish --keys-from-stdin --listen
+ eval 'GUESTFISH_PID=6407;' export GUESTFISH_PID
++ GUESTFISH_PID=6407
++ export GUESTFISH_PID
+ '[' 0 -ne 0 ']'
+ guestfish --remote
libguestfs: error: luks_open: Not enough available memory to open a keyslot.
+ '[' 1 -ne 0 ']'
+ echo 'Failed to resize and sparsify crc_libvirt_2020-06-23/crc-9sqhk-base, aborting'
Failed to resize and sparsify crc_libvirt_2020-06-23/crc-9sqhk-base, aborting
+ exit 1
```

Here is the memory info：
```
$ cat /proc/meminfo
MemTotal:       65700888 kB
MemFree:          666620 kB
MemAvailable:   64261264 kB
Buffers:            3164 kB
Cached:         64172728 kB
```
Any thought for issue? Very appreciate.

**Comment by praveenkumar** [comment]
Looks like you are hitting https://bugzilla.redhat.com/show_bug.cgi?id=1837765 one. as workaround use `export LIBGUESTFS_MEMSIZE=2048` just before executing the `createdisk.sh` or may be mention it in the script.

**Comment by zhangs-ibm** [comment]
@praveenkumar , 
thanks, it works for me! appreciate for your quick answer.

**Comment by gbraad** [comment]
This is not related to the actual machines memory availabilitiy, but what is assigned to the virtualization/emulation environment that Guestfish uses.

**Comment by gbraad** [comment]
> export LIBGUESTFS_MEMSIZE=2048

@praveenkumar Maybe something that should be part of the scripts? Either as a comment or a standard setting. I am sure more will bump into this.

**Comment by praveenkumar** [comment]
@gbraad Agree, it might be the case we also bump into this once update our bundle builder, I am going to reopen this to track and add it as part of script.

**Comment by gbraad** [comment]
This is not an issue with recent releases of Guestfish on RHEL. Since this might be related to older releases let's just close this ...
