### ISSUE TITLE
Avoid running replicas for cluster services 

### ISSUE THREAD

**Issue by gorkem** [code-ready/snc#224]
Remove multiple replicas of the OpenShift cluster workloads as we do not need HA. The following Deployments are the ones that seems to have replicas set to 2 

- `downloads` at `openshift-console` namespace
- `console` at `openshift-console` namespace
-  `openshift-auth` at `openshift-authentication` namespace

## CRC version
```bash
CodeReady Containers version: 1.14.0+36ad776
OpenShift version: 4.5.4 (embedded in binary)
```

**Comment by praveenkumar** [comment]
@gorkem As of now our default approach is run all the workload which is managed by CVO or if we override some of operators (like monitoring, MCO, MCD ..etc.) then set the replica to 0 for them, it will help us to have CVO managed cluster in case some config applied by user (like proxy) to propagate across the cluster. It would be great if we had a console/auth operator config which enable us to set number of replica and still managed by CVO but as of now this is not exist.

Another thing we can do use the profile specific resource data once https://github.com/openshift/enhancements/pull/200 is appeared in the openshift side.

**Comment by praveenkumar** [comment]
With 4.8 this is automatic going to fix because it support the single node cluster and have single replica for each resource.
