### ISSUE TITLE
snc.sh errors out when trying to extract the baremetal image

### ISSUE THREAD

**Issue by daronhudson** [code-ready/snc#235]
When I run the installer I get: 

+ echo 'Extracting installer binary from OpenShift baremetal-installer image'
Extracting installer binary from OpenShift baremetal-installer image
++ ./oc adm release -a /root/snc/pull-secret.yaml info quay.io/openshift-release-dev/ocp-release@sha256:ae61753ad8c8a26ed67fa233eea578194600d6c72622edab2516879cfbf019fd --image-for=baremetal-installer
E0913 17:54:26.268539    2600 config.go:236] while trying to parse blob "apiVersion: v1\ndata:\n  .dockerconfigjson: e30K\nkind: Secret\nmetadata:\n  name: pull-secret\n  namespace: openshift-config\ntype: kubernetes.io/dockerconfigjson\n": invalid character 'a' looking for beginning of value
error: unable to load --registry-config: invalid character 'a' looking for beginning of value
+ baremetal_installer_image=
++ jobs -p
+ kill -9
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
+ true

I'm running centos 7 in a VM with virtualization enabled.

**Comment by praveenkumar** [comment]
@daronhudson what is the version of `oc` you have ? Also check your pull secret file it should be json not the yaml which you download from cloud.openshift.com

**Comment by daronhudson** [comment]
OH my bad. I was doing that part wrong! I'll try it again and update this issue if it works out/doesn't work out. Thank you!

**Comment by daronhudson** [comment]
Alright, it installed but I'm now wondering how I connect to the web console since I have this hosted on a centos 7 server? I have the address for it but can't connect to it from my pc over the network. Also if possible would you have any idea how to change the cluster base address from .testing to my actual domain? Sorry for all the questions, I'm just really new to all of this and would love to be able to start learning and using it for development.

**Comment by praveenkumar** [comment]
https://github.com/code-ready/snc/blob/master/snc.sh#L17 you need to modify this to change the base domain.

**Comment by daronhudson** [comment]
Great thank you for that! Would pointing my domains DNS records to the external address of the machine it's running on allow me to access the console?

**Comment by praveenkumar** [comment]
@daronhudson as long as you DNS record have right mapping about the instance created by installer/snc script.

**Comment by daronhudson** [comment]
Yeah of course. so something like console-openshift-console.apps.10.0.0.2.example.domain being mapped to lets say 1.2.3.4 would still show the console even if it's internally mapped to 192.168.what.ever it happens to be?

**Comment by cfergeau** [comment]
You'd need to configure port forwarding/a proxy/... in order to redirect from 1.2.3.4 to the VM IP

**Comment by daronhudson** [comment]
I wouldn’t have a choice as it’s on a remote server with no other way to access it, all I’d need is access to the openshift console. How would I set that proxy up, if you don’t mind me asking?

**Comment by cfergeau** [comment]
https://code-ready.github.io/crc/#setting-up-remote-server_gsg

**Comment by daronhudson** [comment]
Great! I’ll give that a try. Just one last thing for now, I noticed that when I rebooted my server, I had to run the install script all over again, none of it started back up or anything. Is that normal?

**Comment by daronhudson** [comment]
Also after setting up haproxy and adding the oauth and console urls I get thrown to 

![3585D9C0-7212-4D1A-8B3A-F84A2EE245A1](https://user-images.githubusercontent.com/26112933/93143858-c81c4c80-f6b6-11ea-9424-aae6fef986d9.png)

Is there a list of all the dns records I’d need to map anywhere or a way to get them from the server?

**Comment by daronhudson** [comment]
Nevermind, the above issue only seems to happen on mobile. But the reboot thing is an issue

**Comment by praveenkumar** [comment]
@daronhudson when you reboot the server VM is going to shut down, you need to explicit start the VM when your remote host come up using `virsh autostart <vm_name>` command. I am closing this issue since actual issue is already addressed.
