### ISSUE TITLE
Kubeconfig issues on crc vm

### ISSUE THREAD

**Issue by daronhudson** [code-ready/snc#236]
This is the last issue I’ve got with the setup atm. Whenever I try to use the OC command to do anything cluster related, is days the kubeconfig file isn’t defined(not exact words) and I should point the KUBECONFIG path env variable to the config file. I’ve tried doing that with the /etc/kubernetes/kubeconfig file and also copying the installation config file to the vm and using that but the first one just says permission denied and the second one says openshift-machine-config-operator doesn’t have access to any namespaces.

How can I get around that?

**Comment by cfergeau** [comment]
After a successful `snc.sh` run, the kubeconfig file is in `crc-tmp-install-data/auth/kubeconfig`

**Comment by daronhudson** [comment]
Agni thought it only needed to be copied, sorry. How would I run it?

**Comment by daronhudson** [comment]
Also I'm just using whatever snc happened to install.

**Comment by cfergeau** [comment]
`export KUBECONFIG=crc-tmp-install-data/auth/kubeconfig; ./oc get nodes`

**Comment by cfergeau** [comment]
Closing the issue as I don't think there's a bug here.

**Comment by daronhudson** [comment]
Error from server (Forbidden): nodes is forbidden: User "system:serviceaccount:openshift-machine-config-operator:node-bootstrapper" cannot list resource "nodes" in API group "" at the cluster scope

Found a bug for ya😅 that happens whenever I try to do anything oc related
