### ISSUE TITLE
Issue with service accounts using oc

### ISSUE THREAD

**Issue by daronhudson** [code-ready/snc#238]
Error from server (Forbidden): nodes is forbidden: User "system:serviceaccount:openshift-machine-config-operator:node-bootstrapper" cannot list resource "nodes" in API group "" at the cluster scope.

I ran the kubeconfig file but it just brought more issues.

That's what I get whenever I try to run anything with oc. Sorry for all the questions and problems, I'm just very new to this and greatly appreciate all the help you guys are providing.

**Comment by praveenkumar** [comment]
@daronhudson when are you getting this error, can you provide some more info around it may be some logs?

**Comment by daronhudson** [comment]
I tried running "oc get nodes" and it happens whenever I try to use oc to change a config or kubectl to create a secret or anything really. That's the message I get whenever I run any editing commands and I can't figure out how to get around it.

And more recently it just happened when trying to run:

oc create configmap custom-ca --from-file=ca-bundle.crt=/home/core/ca-bundle.crt -n openshift-config

**Comment by daronhudson** [comment]
I would like to add that the snc installation didn't make a bootstrap node which I found odd

**Comment by praveenkumar** [comment]
@daronhudson if you just want to play around with openshift and don't want to get into the installation then better to use crc https://github.com/code-ready/crc/releases/tag/1.16.0 which uses bundle created by this repo. Also I still don't know what actually failing for you, better to put step by step what you tried and what failed.

**Comment by daronhudson** [comment]
I'd actually like to use it in my production environment but apart from OC not working, which really isn't an issue, I just need to switch out the ingress controller certificate with my own custom one which I don't know how to do without oc, that's my real problem atm

**Comment by daronhudson** [comment]
The step by step was 
- running all the prerequisites for the installation detailed in the one-time setup section
- running the installation which took about 40 minutes and seemed to spit out quite a lot of debug stuff
- attempting to add the kubeconfig to the master node that was created(bootstrap wasn't created for some reason which is why i'm guessing all of this doesn't work)
- setting up a proxy connection to the console for access with haproxy
