### ISSUE TITLE
Reduce max. container log size

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/snc#274]
**Change**

Reduce max. container log size

**How**

Implemented in https://github.com/code-ready/snc/pull/246

**Expected and mesured improvements**

**Pros**

**Cons**

**Comment by praveenkumar** [comment]
Looking into the resource reduction PR  https://github.com/code-ready/snc/pull/280/files#diff-cbe21fe8c80c52627f0b67e6a9172f64800c7ba1f8a730b8186d6c28a985c8f8R80-R101

Which means this is change in the kubelet config, not sure if that will improve anything in terms of resource consumption but we might have less disk usage to save those logs? 

@guillaumerose I am closing this one, can be reopened once we have more details around it on what to implement.
