### ISSUE TITLE
'oc logs' is failing  for all the pods

### ISSUE THREAD

**Issue by spaparaju** [code-ready/snc#283]
For the last 2-3 days or so, I am seeing this problem (after rebasing snc.sh from master)

bash-3.2$ _**oc get pods -n openshift-oauth-apiserver_**
NAME                         READY   STATUS    RESTARTS   AGE
apiserver-856867ff88-zphdw   1/1     Running   0          6h18m
bash-3.2$ _**oc logs -f pod/apiserver-856867ff88-zphdw  -n openshift-oauth-apiserver_**

**_error: You must be logged in to the server (the server has asked for the client to provide credentials ( pods/log apiserver-856867ff88-zphdw))_**

My 'guess' is that the problem is related to Kubelet certs. Recently I see changes related '[renewing certs](https://github.com/code-ready/snc/pull/204)' has been merged.

**Comment by praveenkumar** [comment]
Yes looks like I have broken the CI https://github.com/code-ready/snc/pull/282 should help to make it green but it does need bit more testing.
