### ISSUE TITLE
Resource Limits disable

### ISSUE THREAD

**Issue by PhillipDowney** [code-ready/snc#303]
Is there a way to turn off machine limit enforcement gievn that the machine pool  service is not running in snc ?

**Comment by gbraad** [comment]
can you explain more about what you mean?

**Comment by PhillipDowney** [comment]
so I am working with it on a 8 core 64g memory machine. but even then it only gives me a few cores to play with. What I want to be able to do is over allocate core capacity on the machine in some test and demonstration scenarios. ( knowing none will use their full cpu allocation at the same time.

**Comment by PhillipDowney** [comment]
I forgot to note, currently if 2 systems that default to 4 cores get deployed I am getting services degraded and some not able to start.

**Comment by cfergeau** [comment]
Could `crc config set cpus 8` help with what you are trying to do?

**Comment by praveenkumar** [comment]
@PhillipDowney Are you looking it in the snc side or crc side? On snc side you manually have adjust it for the master node https://github.com/code-ready/snc/blob/master/snc.sh#L145-L147 here or if you are looking for crc then @cfergeau suggested to use `config` option.

**Comment by PhillipDowney** [comment]
CRC side, will try again tomorrow with the above suggestion.
