### ISSUE TITLE
refactor compression to a function

### ISSUE THREAD

**Issue by gbraad** [code-ready/snc#319]
Since some experimentation has been done around compression, it might also help to refactor this and allow for a function for this: 
https://github.com/code-ready/snc/blob/251d56da66b8d31b7baa6df6b04d813a4a8b14f0/createdisk.sh#L191

**Comment by cfergeau** [comment]
Reason for this:
```
createdisk.sh:tar cSf - --sort=name "$libvirtDestDir" | xz --threads=0 >"$libvirtDestDir.$crcBundleSuffix"
createdisk.sh:tar cSf - --sort=name "$hyperkitDestDir" | xz --threads=0 >"$hyperkitDestDir.$crcBundleSuffix"
createdisk.sh:tar cSf - --sort=name "$hypervDestDir" | xz --threads=0 >"$hypervDestDir.$crcBundleSuffix"
```
(the compression command is duplicated 3 times, which means 3 locations to change when updating the compression method).
