### ISSUE TITLE
Don't include `crc_libvirt.sh` in the bundle for libvirt.

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#32]
Right now we are adding the `crc_libvirt.sh` to the bundle that we need to remove.

**Comment by cfergeau** [comment]
And that script could echo a message saying it's only meant for testing purposes, and that people should be using crc instead.

**Comment by cfergeau** [comment]
3rd suggestion comes from gbraad: « Changing the extension of the bundle, to something like `.crcbundle` will prevent people trying to extract it »

**Comment by praveenkumar** [comment]
Fixed by #65
