### ISSUE TITLE
Put VM image file last in the tar archive

### ISSUE THREAD

**Issue by cfergeau** [code-ready/snc#33]
Currently, the files in the archive are in a random order. I believe it should be possible to specify in which order they are by listing all the files explicitly on tar cmdline (instead of just the directory), or by using the -T argument to tar.
The benefit of doing that would be that it would make it much faster to access the smaller files as  we would not need to skip the multi-GB VM image first.

**Comment by guillaumerose** [comment]
Files in the archive are now sorted by name. Not ideal, but the json is at the beginning. https://github.com/code-ready/snc/pull/243

**Comment by anjannath** [comment]
Done in #243
