### ISSUE TITLE
Create auth token which doesn't expire

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#331]
As of now the auth token generated are expired in 24 hours and we need to create the token again by login to cluster. Our cluster is for development purpose so the token shouldn't expire.

- https://docs.openshift.com/container-platform/4.6/rest_api/oauth_apis/oauthclient-oauth-openshift-io-v1.html

**Comment by guillaumerose** [comment]
Fixed in https://github.com/code-ready/snc/commit/91c6799b40ad9a90c67f37f4162c359d92dcdbed
