### ISSUE TITLE
kubeadmin and developer passwords are the same for all clusters

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/snc#333]
As @cfergeau pointed it out, crc rotates the ssh keys. It's is good but it's meaningless if the kubeadmin password and developer password are the same for all clusters in the world.

What could we do for that ?

First, we could drop the kubeadmin account as this password cannot be changed. (see https://access.redhat.com/solutions/5309141)
We could also change the developer password during the first crc start and give him cluster-admin role.

**Comment by praveenkumar** [comment]
We are still forgetting about the kubeconfig file which is part of the bundle and can be used to get access of the cluster doesn't matter if we remove the kube-admin user and it's password and even for developer. Also even if we are generated those user and password as part of crc then also this problem going to persist.

**Comment by guillaumerose** [comment]
What if we don't ship the kubeconfig file (but keep it as part of the VM disk)?

**Comment by praveenkumar** [comment]
@guillaumerose Even you keep it as part of VM disk image the user can able to get it from the disk image or by running the VM.

**Comment by praveenkumar** [comment]
This is not required anymore.
