### ISSUE TITLE
Use HighAvailabilityMode API

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/snc#345]
With OpenShift 4.8, a new API for single node `HighAvailabilityMode=SingleReplica` is available. 
It allows snc to remove most hacks such as reducing the number of replicas of the etcd qurom guard, the unsupported option of the authentication operator, etc. This is now all done with this single option.

https://github.com/openshift/api/commit/56a849fda73ab0c8c668e77b7419aa917d425408
https://github.com/openshift/enhancements/pull/555

**Comment by praveenkumar** [comment]
This is by default added as soon as cluster detect single controlplane, we need to branch 4.7 and use the master for 4.8 side  after current release.

**Comment by guillaumerose** [comment]
Yes it's here! 
https://github.com/openshift/installer/blob/master/pkg/asset/manifests/infrastructure.go#L99
