### ISSUE TITLE
Pull dnsmasq container image before creating the disk image

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#35]
As of now we are going to use `quay.io/crcont/dnsmasq:latest` as part of internal dns resolution so it would be great to have it in as part of disk image then pulling it from the registry everytime a user start the cluster.

**Comment by gbraad** [comment]
might be over time we need to add provisioning to allow skopeo (or something else) to insert images that have been pre-made/cached/or downloaded from the node that builds the images. this way we can verify the images BEFORE adding them to the image.
