### ISSUE TITLE
Add default registry route as part of insecure registry for the node

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#355]
On crc right now we expose the default registry route where user can push the images but as soon as they use this registry with image stream it failed with ` Failed to pull image "default-route-openshift-image-registry.apps-crc.testing/demo/rook:latest": rpc error: code = Unknown desc = error pinging docker registry default-route-openshift-image-registry.apps-crc.testing: Get "https://default-route-openshift-image-registry.apps-crc.testing/v2/": x509: certificate signed by unknown authority` which means this registry route should be added as part of insecure registry as described https://docs.openshift.com/container-platform/4.7/openshift_images/image-configuration.html#images-configuration-insecure_image-configuration here.

**Comment by cfergeau** [comment]
We probably can get access to the CA used for `default-route-openshift-image-registry.apps-crc.testing`? If yes, we should follow https://docs.openshift.com/container-platform/4.7/openshift_images/image-configuration.html#images-configuration-cas_image-configuration instead

**Comment by cfergeau** [comment]
> Closing this since it suppose to be this way for k8s/openshift side, we need to tell user to use internal registry service endpoint for image.

If they add/use a pull secret, and use the correct CA, would it work with the external registry endpoint? Or are you saying that even on a production OpenShift installation, it's better to use the internal registrey service?
