### ISSUE TITLE
Explain how to build virtualbox image to run on OSX

### ISSUE THREAD

**Issue by skabashnyuk** [code-ready/snc#37]
As I understand with this issue https://github.com/code-ready/snc/issues/13 to the code was added script that can build virtualbox images. It would be nice to see somewhere explanation of how to use it. Can you share command example how to use it?

**Comment by cfergeau** [comment]
We don't really expect end-users to directly run the snc script, but rather to use pre-built bundles together with the 'crc' tool ( https://github.com/code-ready/crc ). At the moment there were no public releases of these pre-built bundles though as there are a few issues to solve before we can do that.

The README file should be up to date regarding the creation of the image ( https://github.com/code-ready/snc/blob/master/README.md ), but then I'm not sure where the documentation is regarding using/running the resulting image :)

**Comment by skabashnyuk** [comment]
ok

**Comment by gbraad** [comment]
We can explain how to build, and from CRC you find how to run, but as mentioned this is not our usecase. The images are to be used with CRC as they have to rely on additional infra for macOS, like DNS.
