### ISSUE TITLE
Use second in the date timestamp when creating the directory

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#383]
Since we are using a same GCP bucket for all the bundles produced by snc/installer PR and right now the bundles directory structure depend on the https://github.com/code-ready/snc/blob/master/createdisk-library.sh#L14 date which means new bundles override old one if produced on same day so better to include seconds field as part of directory creation.

**Comment by cfergeau** [comment]
Maybe it's possible to add the PR number in the directory structure? Only keeping the latest bundles for a PR should be good enough, and will save some space.

**Comment by praveenkumar** [comment]
@cfergeau yes that also a possible solution, will  try that.
