### ISSUE TITLE
Add hyperkit support

### ISSUE THREAD

**Issue by cfergeau** [code-ready/snc#39]
hyperkit support needs additional files/metadata:
- we need to get the correct vmlinuz and initramfs, probably extracting them from the VM image
- `crc-bundle-info.json` needs to describe these files
- then we'll either need to also extract the full kernel command line for use by hyperkit, or add the ostree hash, the disk uuid, and the boot 'index' to the metadata file. The full kernel command line is similar to `CMDLINE="BOOT_IMAGE=/ostree/rhcos-$OSTREE_HASH/$KERNEL console=tty0 console=ttyS0,115200n8 rootflags=defaults,prjquota rw root=UUID=$ROOT_UUID ostree=/ostree/boot.0/rhcos/$OSTREE_HASH/0 coreos.oem.id=qemu ignition.platform.id=qemu"` (the so called 'boot index' is the '0' which appears twice in the `ostree=...` bit). This data will go in `crc-bundle-info.json`

**Comment by praveenkumar** [comment]
fixed by #48
