### ISSUE TITLE
Wait until the VM is shutdown after `virsh shutdown` call

### ISSUE THREAD

**Issue by cfergeau** [code-ready/snc#41]
`createdisk.sh` calls `virsh shutdown` to cleanly stop the crc VM. However, this call is asynchronous, so if we don't wait until the image is fully shutdown, the next step could end up working from a corrupted image (because it was being modified while we were reading it).
Calling `virsh event` would hopefully do that job for us without needing to poll. Alternatively `virsh domstate` will tell us if the VM is still running or not.

**Comment by praveenkumar** [comment]
fixed by #42
