### ISSUE TITLE
Run dnsmasq as service instead just a container

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#411]
When MCO is enabled and we make some changes to config which require reboot then after reboot dnsmasq container is not running, It should be good to have it as part of systemd unit instead running independently using podman.

**Comment by cfergeau** [comment]
Maybe this is already the suggestion, but podman containers can be started as systemd services relatively easily, see https://www.redhat.com/sysadmin/improved-systemd-podman

**Comment by praveenkumar** [comment]
This is also fixed and now part of the master.
