### ISSUE TITLE
api.crc.testing is hardcoded in snc-library.sh

### ISSUE THREAD

**Issue by danielmenezesbr** [code-ready/snc#421]
[api.crc.testing](https://github.com/code-ready/snc/blob/master/snc-library.sh#L73-L77) is hardcoded in snc-library.sh

Instead, it's should be based on the variable [BASE_DOMAIN](https://github.com/code-ready/snc/blob/master/snc.sh#L25). For instance, api.crc.$BASE_DOMAIN

**Comment by cfergeau** [comment]
Yup, that's an oversight. Most of the code even use ` api.${CRC_VM_NAME}.${BASE_DOMAIN}` to avoid hardcoding `crc`.
Are you planning to provide a PR to fix this? I'll fix this next week otherwise :)

**Comment by danielmenezesbr** [comment]
@cfergeau PR #427 created.
