### ISSUE TITLE
Branch out 4.8 and use master for 4.9

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#440]
Code freeze for 4.8 happened and rc bits are available. For snc side it is time to branch 4.8 and use master for 4.9 development phase.
- A release job also need to be added for 4.8 branch on https://github.com/openshift/release/blob/master/ci-operator/jobs/code-ready/snc/

**Comment by praveenkumar** [comment]
https://github.com/openshift/release/pull/19527 for release job.

**Comment by cfergeau** [comment]
This means we'll have 3 active branches in parallel. Is it required that we does that switch now, or can we delay this until crc switches to 4.8?

**Comment by praveenkumar** [comment]
> This means we'll have 3 active branches in parallel. Is it required that we does that switch now, or can we delay this until crc switches to 4.8?

We do need to switch eventually and it's better to do it now since rc bits are released instead waiting. There is no issue with having 3 branches we will file an PR to remove 4.7 when 4.8 is part of crc release since we don't require to maintain 4.7 branch.

**Comment by praveenkumar** [comment]
This is fixed now.

/close
