### ISSUE TITLE
How do I preserve the machine/cluster state after executing the snc.sh script?

### ISSUE THREAD

**Issue by danielmenezesbr** [code-ready/snc#445]
If I reboot the machine after running `snc.sh`, the cluster/VM is recreated again.

How do I preserve the machine/cluster state after executing the `snc.sh` script?

**Comment by praveenkumar** [comment]
@danielmenezesbr if you reboot the host machine then respective VM on which cluster is running is stopped so if after the reboot you can check `sudo virsh list --all` and then start that vm using `sudo virsh start <vm_name>` should work for you.

**Comment by danielmenezesbr** [comment]
@praveenkumar, thank you.
