### ISSUE TITLE
Run out of disk space in /run

### ISSUE THREAD

**Issue by ChrisPhillips-cminion** [code-ready/snc#453]
OKD 4.7 latest stable 4.7.0-0.okd-2021-07-03-190901

Master vm does not start SSH
Bootstrap allows me to log in but run is only 785mb

form journal -xe
```
Jul 09 22:15:05 crc-94vqd-bootstrap kubelet-pause-image.sh[6437]: Error: error creating container storage: write /run/containers/storage/overlay-layers/.tmp-mountpoints.json401828690: no space left on device
```

```
[core@crc-94vqd-bootstrap ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        1.9G     0  1.9G   0% /dev
tmpfs           2.0G   84K  2.0G   1% /dev/shm
tmpfs           785M  785M     0 100% /run
/dev/vda4        20G  3.0G   17G  16% /sysroot
tmpfs           2.0G     0  2.0G   0% /tmp
/dev/vda3       364M   90M  252M  27% /boot
[core@crc-94vqd-bootstrap ~]$
``` 

How big does /run need to be? how do we increase it?

**Comment by gbraad** [comment]
Please use the disk resize option.

**Comment by gbraad** [comment]
Note: We do not support he OKD releases. This is done by the community and issues need to he filed at github.com/openshift/okd

**Comment by praveenkumar** [comment]
CC @cgruver

**Comment by cgruver** [comment]
@ChrisPhillips-cminion 

Set the following before running `snc.sh`

`export TF_VAR_libvirt_bootstrap_memory=16384`

**Comment by cfergeau** [comment]
Could be related to https://github.com/openshift/installer/pull/5069#pullrequestreview-703859941 ?

**Comment by cgruver** [comment]
Yes, I believe that change will make it unnecessary to set the above mention terraform variable.
