### ISSUE TITLE
snc.sh fails due to missing metadata.json file

### ISSUE THREAD

**Issue by dharmit** [code-ready/snc#47]
I followed the steps mentioned in the README page and executed `./snc.sh` after copying the `openshift-install` binary. But it fails with below output:

```bash
$ ./snc.sh
/home/dshah/bin/oc
/home/dshah/src/snc/yq
/usr/bin/jq
DEBUG OpenShift Installer unreleased-master-1133-ga99bd59f377226102c146befca60e948f0c601c8 
DEBUG Built from commit a99bd59f377226102c146befca60e948f0c601c8 
FATAL Failed while preparing to destroy cluster: open crc-tmp-install-data/metadata.json: no such file or directory 
OpenShift pull secret must be specified through the OPENSHIFT_PULL_SECRET environment variable
```
There is indeed no `metadata.json` file:
```bash
$ ls -a crc-tmp-install-data
.  ..  .openshift_install.log
```
I'm trying to do this on Fedora 30 system. Also, what's `OPENSHIFT_PULL_SECRET` supposed to be set to?

**Comment by cfergeau** [comment]
The real issue is OPENSHIFT_PULL_SECRET not being set, the other error is actually non-fatal (it was fatal for openshift-install, but not for snc.sh). We should indeed add some documentation for OPENSHIFT_PULL_SECRET, openshift-install says:
```
The container registry pull secret for this cluster, as a single line of JSON (e.g. {"auths": {...}}).

You can get this secret from https://cloud.openshift.com/clusters/install#pull-secret
```

**Comment by praveenkumar** [comment]
@dharmit I am curious to know what is your usecase doing that instead not using the `crc` directly with latest bundle?

**Comment by dharmit** [comment]
> @dharmit I am curious to know what is your usecase doing that instead not using the `crc` directly with latest bundle?

Lack of awareness. I want to have a minishift like setup but for 4.0. Looking at an email, I thought I *had* to go through SNC since it's Single Node Cluster. But I missed that tarball is available for download.
