### ISSUE TITLE
Add driver info to the bundle metadata file

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#49]
We should also have driver info in the bundle metadata file so some sanity check we do when user run against with a specific bundle.

**Comment by anjannath** [comment]
```json
"driverInfo": {
    "name": "libvirt"
  }
```
Just the driver name for now i guess, or any other information we need to include, like minimum supported version, dependencies?

**Comment by praveenkumar** [comment]
fixed by #59
