### ISSUE TITLE
Don't disable the marketplace operator

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#50]
Right now we are disabling the marketplace operator by default but it is not talking much resource like we anticipated, also most of the operator developer need it during the development phase and even user need to get some operator for it.

**Comment by gbraad** [comment]
we could decide to have this being enabled as a post deployment instead. this way we can leave it disabled, but we enabled a way to enable operators.

**Comment by praveenkumar** [comment]
This operator is not taking a lot of resources and also most of developer or user need it to be present for openshift-4 side.

**Comment by praveenkumar** [comment]
resolved by #53
