### ISSUE TITLE
Bundle name should also contain ARCH details

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#504]
As of now our bundle named as `crc_podman_hyperv/hyperkit/libvirt_3.4.2.crcbundle` which should take arch in account so that all the bundles can be in same location something like `crc_podman_hyperv/hyperkit/libvirt_3.4.2_${ARCH}.crcbundle`.

**Comment by cfergeau** [comment]
This should also be added to the bundle metadata if it's not present yet.

**Comment by praveenkumar** [comment]
It if fixed and arch info is part of bundle metadata also.
