### ISSUE TITLE
Add sha256sum for the disk image to metadata

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#52]
We should add the disk image sha256sum in the metadata so we can easily able to cross-check the used disk image.

**Comment by cfergeau** [comment]
and disk size too for quick sanity checks (this would help detect truncated disk images because there was a failure when uncompressing it)

**Comment by anjannath** [comment]
This info would go under `storage` right?

```json
"storage": {
    "diskImages": [
      {
        "name": "crc.qcow2",
        "format": "qcow2",
        "size": "1.2G",
        "sha256sum": "xxxxxxxxxxxxxxxxx"
      }
    ]
  }
```

**Comment by cfergeau** [comment]
> This info would go under `storage` right?

Yes, looks like it :) Size would most likely be in bytes as we want the exact size.

**Comment by praveenkumar** [comment]
@cfergeau @anjannath do we really need the disk size, doesn't shasum will be helpful if there is issue with decompression ?

**Comment by cfergeau** [comment]
checking disk size during startup is almost free, computing the sha256sum of several GiB is much more costly, and not something which can be done as a preflight start check. So I'd put both, one for fast checks, the other one is more accurate, but costlier too.

**Comment by praveenkumar** [comment]
@cfergeau make sense, thanks 👍
