### ISSUE TITLE
Add preset info to bundle metadata

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#558]
Currently ocp/okd doesn't have any differentiator on bundle metadata level. It is bit hard to detect the bundle mismatch on crc side. We should add the `preset` to bundle metadata which would be set as openshift/okd as per bundle type.

**Comment by cfergeau** [comment]
This can be done with the existing `type` field, which crc already maps to a preset: https://github.com/code-ready/crc/blob/b91afcd751135be1d3955f1c714d70b99bd4db93/pkg/crc/machine/bundle/metadata.go#L176-L187

**Comment by praveenkumar** [comment]
@cfergeau existing `type` filed is same for okd/ocp bundle. so I think better to have this `preset` filed?

**Comment by cfergeau** [comment]
Depends if there's a strong technical reason for using `snc` for OKD? Or is this just something which was missed when OKD support was added? It seems simpler to just have one field for the bundle type, instead of having to look at 2 fields.

**Comment by praveenkumar** [comment]
@cfergeau when we added `snc` it was for `single node cluster` and it true for OKD/OCP side. Initial plan was if we ever have multi node cluster then we should use this `type` field to distinguish. Do you want to have `snc` and `snc-okd` kind of differentiation?

**Comment by cfergeau** [comment]
When podman was added, we used this field to make the distinction between podman and openshift. I would use it also for okd as it seems simpler/easier to understand/...

**Comment by praveenkumar** [comment]
@cfergeau My question is should we go with `snc/snc-okd` or `openshift/okd` for it. I am tend to go with `snc-okd` so that older bundle of ocp side still works. I am open for suggestion.

**Comment by cfergeau** [comment]
Yes, we would keep `snc` for openshift bundles, I don't think it's worth the complication to rename it. I would use just `okd`, but `snc-okd` is fine too.

**Comment by praveenkumar** [comment]
I will just go for `okd` because I don't think now we are going to go with multinode cluster (looking at the resource consumption)

**Comment by cfergeau** [comment]
even if we do, we can use `openshift-mnc` and `okd-mnc`

**Comment by praveenkumar** [comment]
Updated PR with `okd` as type.

**Comment by praveenkumar** [comment]
This is now part  of the bundle.
