### ISSUE TITLE
change the vbox to virtualbox for the bundle creation

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/snc#56]
We should put our bundle name according to the hypervisor driver flag which we use in the crc to make it consistent. 

- libvirt 
- virtualbox
- hyperkit
- hyperv

**Comment by gbraad** [comment]
workaround in CRC: https://github.com/code-ready/crc/pull/273#discussion_r298935527 would have to be removed at the same time.

**Comment by praveenkumar** [comment]
fixed by #59
