### ISSUE TITLE
openshift-client-mac download url not available on mirror ocp-dev-preview

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/snc#585]
Currently mac client download url has been set as a "fixed" valid version for mac client as workaround for https://github.com/code-ready/snc/issues/576 

The version used as workaround `stable-4.10` is not available at https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/ , this will prevent using snc master branch for building preview OCP versions.

**Comment by cfergeau** [comment]
This should be using https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.10/ instead of `${MIRROR}/stable-4.10/openshift-client-mac.tar.gz`

When you build preview OCP versions, are they 4.11 or 4.12 versions?

**Comment by adrianriobo** [comment]
now I am building 4.12

**Comment by cfergeau** [comment]
> actually there was that discussion in the past to create a "next" branch ..or just "release-4.n"

This is why I was asking which version you are building for. Maybe we should have such a branch with https://github.com/code-ready/snc/pull/586/commits/f73a4dc5524bff9f126ddff757a04448b5f6af28 reverted so that latest `oc` is possibly tested on macOS.

**Comment by adrianriobo** [comment]
yeah. definitely that would work too
