### ISSUE TITLE
Clearer naming for disk image

### ISSUE THREAD

**Issue by gbraad** [code-ready/snc#6]
Can we have clearer naming for the disk image?
https://github.com/praveenkumar/snc/blob/5aa1c220db8c5e57c7de999c706c1702744d50a8/createdisk.sh#L36

something like `system.img` ?

**Comment by cfergeau** [comment]
I'm planning to add an extension to the image, however as it currently is in the 'default' pool, it's better to use naming which makes it clear the image is related to code ready containers.

**Comment by gbraad** [comment]
However, when used with libmachine and the driver, the image will live in the user's home directory

**Comment by gbraad** [comment]
described in metadata
