### ISSUE TITLE
Remove archive (tar.xz) extension from the bundles

### ISSUE THREAD

**Issue by anjannath** [code-ready/snc#60]
/cc @gbraad

**Comment by gbraad** [comment]
something like `.imagebundle` or just `.images` would make sense

**Comment by cfergeau** [comment]
I'd go for `.crcbundle` I think

**Comment by praveenkumar** [comment]
yes same here `.crcbundle` make more sense. So the names will be `crc_libvirt.crcbundle` like that?

**Comment by cfergeau** [comment]
With a version number I think? `crc_libvirt_4.1.3.crcbundle`? Though if this ends up embedded in the crc binary, naming becomes an implementation detail.

**Comment by praveenkumar** [comment]
Yes I meant with version info :) doesn't this will case any issue when it comes to extract it as part of our crc codebase? @anjannath can you double check this one.

**Comment by anjannath** [comment]
@praveenkumar It shouldn't, but sure i'll check it to make sure..

**Comment by praveenkumar** [comment]
fixed by #59
